services:
  ia_apt:
    hostname:         ia_apt.innovanon.com
    build:
      context:        .
      tags:
        - innovanon/ia_apt:latest
        -           ia_apt:latest
        - innovanon/ia_apt
        -           ia_apt
    restart:          no
    logging:
      driver:         syslog   
