services:
  ia_apt:
    hostname:         ia_apt.innovanon.com
    build:
      context:        .
      tags:
        - ia_apt:latest
    restart:          no
    logging:
      driver:         syslog   
